services:
    ttbb-mern-back:
        image: janzu/ttbb-mern-back
        ports: 
            - "5000:5000"
        networks:
            - app-network
        
    ttbb-mern-front:
        image: janzu/ttbb-mern-front
        ports:
            - "3000:3000"
        networks:
            - app-network
            
networks:
    app-network:
        driver: bridge
        